// List of profanities to be filtered
let profanities = ['fuck', 'shit','dick','jigaboo',	'asslover',	's&m',	'whitetrash',	'meatrack',	'pimp',	'urine',	'herpes',	'niglet',	'narcotic',	'rimming', 'boner',	'pornography',	'poop chute',	'muffdiving',	'jiggabo',	'peepshpw',	'popimp',	'girl on',	'testicles',	'laid',	'molestor',	'peni5',	'arsehole',	'shitty ',	'cunilingus',	'bitcher',	'pee',	'niggled', 'cocksman', 'scag',	'niggling',	'fingerfucker ',	'nlggor',	'niggaz',	'assfuck',	'urinate',	'mothafucked ',	'retard',	'gummer',	'mickeyfinn',	'fuckers','bukkake', 'shag',	'australian',	'raped',	'buggery',	'weenie',	'lickme',	'reverse cowgirl',	'tonguetramp',	'cum',	'copulate',	'schlong',	'cunn',	'damnit',	'crackpipe',	'buttmuncher',	'cameltoe',	'camgirl',	'hotpussy',	'cuntfucker',	'sluts',	'ball licking',	'hentai',	'jackshit',	'dickman',	'cumm',	'cuntlicking ',	'vibrater',	'jijjiboo',	'fuckfriend',	'pthc',	'mothafucka',	'sniggered',	'buttfuckers',	'nutfucker',	'peehole',	'taboo',	'erection',	'nudity',	'hummer',	'shortfuck',	'cherrypopper',	'adult',	'pussylips',	'stiffy',	'piss pig',	'beastiality',	'gross',	'crackwhore',	'butt-fuckers',	'kraut',	'pooping',	'style doggy',	'lactate',	'fecal',	'rusty trombone',	'wrinkled starfish',	'spigotty',	'dink',	'clogwog',	'whitey',	'dies',	'slaughter',	'bollick',	'sodomite',	'balls',	'double penetration',	'missionary position',	'bugger',	'lovejuice',	'handjob',	'nlgger',	'sonofabitch',	'goddamned',	'deep throat',	'jism',	'assclown',	'shitforbrains',	'screwyou',	'nastyslut',	'gang bang',	'lubejob',	
'abortion',	'murderer',	'motherfucker',	'doggy style',	'cunntt',	'cooly',	'ball sack',	'sodom',	'slideitin',	'fudge packer',	'fatfuck',	'gipp',	'felatio ',	'libido',	'xtc',	'cuntfuck',	'niggardly',	'fuckface',	'faggot',	'trailertrash',	'headfuck',	'shav',	'dickweed',	'trannie',	'giant cock',	'sexhound',	'slut',	'titlover',	'wank',	'moslem',	'krappy',	'cock',	'idiot',	'tortur',	'erotic',	'cockcowboy',	'sucker',	'cocktail',	'fastfuck',	'kondum',	'pansy',	'ikey',	'titfuck',	'cummer',	'kumquat',	'one guy one jar',	'carruth',	'cocktease',	'trisexual',	'pric',	'rabbi',	'gypp',	'cunnilingus',	'dipshit',	'welfare',	'transvestite',	'tnt',	'penile',	'mothafuckings',	'peckerwood',	'negroid',	'genital',	'gangbanger',	'queef',	'strapon',	'female squirting',	'ejaculate',	'carpet muncher',	'bondage',	'kumbullbe',	'niggerhole',	'niggard',	'rosy palm',	'bastard ',	'asspuppies',	'jiggerboo',	'cuntlick ',	'pommie',	'doggie style',	'lezz',	'nazi',	'feltch',	'chode',	'pleasure chest',	'wetback',	'zipperhead',	'necro',	'goddamnmuthafucker',	'whiskeydick',	'slopy',	'turnon',	'nofuckingway',	'mastrabator',	'jack off',	'orgies',	'pisses ',	'blow j',	'criminals',	'cockqueen',	'tosser',	'snownigger',	'holestuffer',	'dipstick',	'mofo',	'nipplering',	'minority',	'italiano',	'palesimian',	'horn',	'rape',	'genitals', 
'fingering',	'cock',	'osama',	'mothafucking ',	'wetb',	'freefuck',	'rere',	'goatse',	'transexual',	'bunghole',	'assholes',	'butt-fuck',	'nig nog',	'snowback',	'gangbang',	'cockfight',	'mggor',	'skankbitch',	'goy',	'twat',	'masturbate',	'usama',	'babeland',	'dickwad',	'cornhole',	'nigra',	'fuckinright',	'clit',	'niggle',	'timbernigger',	'picaninny',	'whorefucker',	'nigg',	'femdom', 'raping', 'moky',	'futanari',	'nigger',	'skinflute',	'throating',	'asspacker',	'leather straight jacket',	'raghead',	'crotch',	'goo girl',	'knobbing',	'buttman',	'glazeddonut',	'urethra play',	'fairies',	'fuckmehard',	'shaved pussy',	'bitchin',	'cocks',	'fucker',	'gyppie',	'kinkster',	'penthouse',	'biatch',	'wop',	'erect',	'fag',	'fuck',	'shitfull',	'vaginal',	'flasher',	'sexpot',	'sexymoma',	'boonie',	'puke',	'buttcheeks',	'cacker',	'bdsm',	"negro's",	'lesbian',	'hustler',	'nipples',	'dumbfuck',	'backdoor',	'wuzzie',	'sadom',	'threeway',	'pimpjuic',	'brown showers',	'pubes',	'masturbating',	'bollocks',	'bunga',	'sodomize',	'goddammit',	'footstar',	'goatcx',	'chink',	'butthead',	'spermbag',	'jailbait',	'beatoff',	'incest',	'vagina',	'urophilia',	'niggarded',	'kaffer',	'rearentry',	'motherfucking',	'spic',	'areola',	'greaseball',	'loverocket',	'asshore',	'perv',	'fingerfood',	'muff',	'shaggin',	'commie',	'hitler',	'honky',	'tongue',	'fubar',	'dildo',	'sniggering',	'omorashi',	
'pedophile',	'stupidfucker',	'beastial',	'shithead',	'asses', 'pussylover',	'niggah',	'gotohell',	'jigga',	'remains',	'frotting',	'thirdeye',	'fuckknob',	'inthebuff',	'nawashi',	'roundeye',	'retarded',	'mastabate',	'disturbed',	'kunnilingus',	'bung hole',	'pee-pee',	'camwhore',	'satan',	'lowlife',	'tubgirl',	'fucks',	'diseases',	'blow your l',	'krap',	'addicts',	'snatchpatch',	'poontang',	'snatch',	'pussypounder',	'shit',	'pu55i',	'footaction',	'footlicker',	'bimbos',	'mothafuckaz',	'pussycat',	'fucking',	'funfuck',	'piece of shit',	'boang',	'nipple',	'fuckit',	'quim',	'booty call',	'slutting',	'coitus',	'tit',	'spermherder',	'raging boner',	'buttfucker',	'quickie',	'grope',	'skum',	'kanake',	'soviet',	'honkers',	'chinky',	'dingleberry',	'shota',	'hillbillies',	'godammit',	'fugly',	'nasty',	'ejaculation',	'waysted',	'carpetmuncher',	'nastybitch',	'camel toe',	'strappado',	'limpdick',	'heroin',	'polack',	'pornprincess',	'gonorrehea',	'meatbeatter',	'crotchmonkey',	'shithappens',	'foot fetish',	'canadian',	'amateur',	'uck',	'whitenigger',	'niger',	'bigger',	'squaw',	'hand job',	'buttbang',	'titty',	'gypo',	'defecate',	'kock',	'niggaracci',	'pussyfucker',	'corruption',	'girls gone wild',	'boobs',	'ejaculated',	'shitface',	'autoerotic',	'creamy',	'bible',	'fckcum',	'knockers',	'fucck',	'whorehouse',	'cocksmoker',	'queer',	'cocklover',	'assblaster',	'bombing',	'hooters',	'forni',	'kike',	'hapa',	'bazooms',	'vulva',	'fuckfreak',	'snot',	'cuntsucker',	'fingerfucked ',	'scallywag',	'pixy',	'kkk',	'mastabater',	'byatch',	'whigger',	'sos',	'pussy',	'group sex',	'attack',	'fucktard',	'nook',	'marijuana',	'asscowboy',	'fatso',	'spit',	'bazongas',	'chickslick',	'joint',	'niggards',	'cockblocker',	'gob',	'lingerie',	'anal',	'headlights',	'dike',	'pegging',	'kaffre',	'taste my',	'crack-whore',	'lynch',	'tub girl',	'bullshit',	'explosion',	'homosexual',	'fucked',	'lesbin',	'fellatio',	'nudger',	'boonga',	'choad',	'cra5h',	'tuckahoe',	'fingerfucking ',	'hijacker',	'athletesfoot',	'pom',	'livesex',	'cocknob',	'nude',	'fuckbag',	'hobo',	'gyp',	'kyke',	'stupid',	'radicals',	'figging',	'fuckfest',	'hottotrot',	'kinbaku',	'sexhouse',	'violet wand',	'analsex',	'nigga',	'nittit',	'jiz ',	'suckmydick',	'pussies',	'hotdamn',	'assfucker',	'jizim',	'pixie',	'kum',	'rigger',	'ethical slut',	'dolcett',	'ejaculating ',	'cumquat',	'eatpussy',	
'phuk',	'givehead',	'phukking',	'shiteater',	'hooker',	'cocksuck ',	'cocksucker',	'ball kicking',	'fuckyou',	'crappy',	'feltching',	'ribbed',	'dog style',	'interracial', 'tanga', 'gago', 'putangina', 'bubu', 'gaga', 'gagi', 'pota', 'puta', 'putanginamo', 't@nga', 't@ng@', 'tanginaka','tangina','tanginamo','kinangina','kinginamo','kingina ka','burat','etits','iyot','kantot','kinantot','kakantunin','binuburat','pekpek','walang hiya','punyeta','lintik','letse', 'kepyas', 'tarantado', "amputa","animal ka","bilat","binibrocha","bobo","bogo","boto","brocha","burat","bwesit","bwisit","demonyo ka","engot","etits","gaga","gagi","gago","habal","hayop ka","hayup","hinampak","hinayupak","hindot","hindutan","hudas","iniyot","inutel","inutil","iyot","kagaguhan","kagang","kantot","kantotan","kantut","kantutan","kaululan","kayat","kiki","kikinginamo","kingina","kupal","leche","leching","lechugas","lintik","nakakaburat","nimal","ogag","olok","pakingshet","pakshet","pakyu","pesteng yawa","poke","poki","pokpok","poyet","pu'keng","pucha","puchanggala","puchangina","puke","puki","pukinangina","puking","punyeta","puta","putang","putang ina","putangina","putanginamo","putaragis","putragis","puyet","ratbu","shunga","sira ulo","siraulo","suso","susu","tae","taena","tamod","tanga","tangina","taragis","tarantado","tete","teti","timang","tinil","tite","titi","tungaw","ulol","ulul","ungas"];
// Regular expression pattern to match profanities
let profanityPattern = new RegExp(profanities.join('|'), 'gi');
new RegExp()
// Function to update the profanity pattern based on the current list of profanities
function updateProfanityPattern() {
  profanityPattern = new RegExp(profanities.join('|'), 'gi');
}

// Function to replace profanities with asterisks
function replaceProfanities(text) {
  return text.replace(profanityPattern, function(match) {
    return '*'.repeat(match.length);
  });
}

// Function to filter the text content of all elements on the page
function filterPageContent() {
  // Select all elements with text content on the page
  const textElements = document.querySelectorAll('*');

  textElements.forEach(element => {
    // Check if the element has text content
    if (element.childNodes.length === 1 && element.childNodes[0].nodeType === Node.TEXT_NODE) {
      element.textContent = replaceProfanities(element.textContent);
    }
  });
}
// Observe changes in the DOM to trigger the profanity filter
const observer = new MutationObserver(filterPageContent);
observer.observe(document.body, {
  childList: true,
  subtree: true,
});

updateProfanityPattern();

